### ISSUE TITLE
@animation(True)時の処理において、CPU負荷が高くなる

### ISSUE THREAD

**Issue by ClairdelunaEve** [aais-lab/IntroductionPrograming-library#4]
### 概要
animationデコレータをTrueにした際、n回目の関数の処理が終わる前に、afterからn+1回目の関数が呼び出されCPUで処理待ちが発生する

### 状況
現在のanimationデコレータ処理は
1. animationのT/Fに応じてCanvasをクリア
2. animationデコレータが発行された関数を実行
3. globalで指定されたRATEを実行間隔(ms)としてtkinterのafterに登録
4. 指定ms経過後、afterがanimationデコレータが指定された関数を呼び出し再度1から実行

この状況下において、以下条件のいずれかが該当した場合にCPU負荷が高まりアプリケーションが遅延する。
- ユーザがanimationSpeed関数で指定したRATEもしくはdefaultのRATEが実際の関数処理時間よりも短い
- メモリ、CPU等の実行に関わるPCのスペックが低い
- animationデコレータ発行関数の中でファイル読み込み等の処理が含まれている(関数処理時間が長くなりI/O待ちが発生する)

### 対応
animationデコレータ発行関数の処理時間を基準として、afterの時間を決定する形式に変更する
検討している処理は以下
1. animationのT/Fに応じてCanvasをクリア
2. 現時点のmsを取得
3. animationデコレータが発行された関数を実行
4. 関数の処理時間を算出
5. 算出した処理時間が指定されたRATEよりも小さい場合、RATEを採用
6. 算出した処理時間が指定されたRATEよりも大きい場合、関数の処理時間を採用
7. 採用されたmsをafter関数の実行間隔として登録
8. 指定ms経過後、afterがanimationデコレータが指定された関数を呼び出し再度1から実行

### タスク
- [x] animationデコレータの処理を上記対応のとおりに修正する
- [x] PCスペックを変更して検証する

**Comment by NaoYamanouchi** [comment]
関数の処理時間が2sを超えた場合、標準出力に処理が重い旨を通知する

**Comment by ClairdelunaEve** [comment]
## 概要
処理時間に合わせて描画処理の速度を変更するようにした

## 新規追加
- 処理が重い旨を通知する例外：ProcessingIsLaggy

## 変更
### animationデコレータ内のafter関数へ登録する秒数決定アルゴリズム
#### 元
animationSpeed関数もしくは既定のRATEが指示するミリ秒
#### 変更後
- animationSpeed関数もしくは既定のRATEが指示するミリ秒
- RATEよりもデコレータが付与された関数の処理時間が長い場合は、関数の処理時間
処理時間の計測にはtimeモジュールのperf_counterを使用している
